packages:
  - src/**
  - "!**/test-data/**"
  - "!**/dist/**"

# Shared version expressions (yaml anchors).
# This is a yaml feature and is not interpreted by pnpm directly.
__versions:
  - &react_version ^19.1.1
  - &core_packages_version ^4.1.0
  - &ol_base_packages_version ^0.11.0

# https://pnpm.io/catalogs
catalog:
  # Trails OpenLayers base packages
  # https://github.com/open-pioneer/trails-openlayers-base-packages
  "@open-pioneer/basemap-switcher": *ol_base_packages_version
  "@open-pioneer/coordinate-viewer": *ol_base_packages_version
  "@open-pioneer/geolocation": *ol_base_packages_version
  "@open-pioneer/map-navigation": *ol_base_packages_version
  "@open-pioneer/map-ui-components": *ol_base_packages_version
  "@open-pioneer/map": *ol_base_packages_version
  "@open-pioneer/measurement": *ol_base_packages_version
  "@open-pioneer/overview-map": *ol_base_packages_version
  "@open-pioneer/scale-bar": *ol_base_packages_version
  "@open-pioneer/scale-viewer": *ol_base_packages_version

  # Trails core packages
  # https://github.com/open-pioneer/trails-core-packages
  "@open-pioneer/base-theme": *core_packages_version
  "@open-pioneer/core": *core_packages_version
  "@open-pioneer/chakra-snippets": *core_packages_version
  "@open-pioneer/http": *core_packages_version
  "@open-pioneer/integration": *core_packages_version
  "@open-pioneer/notifier": *core_packages_version
  "@open-pioneer/react-utils": *core_packages_version
  "@open-pioneer/reactivity": *core_packages_version
  "@open-pioneer/runtime": *core_packages_version
  "@open-pioneer/test-utils": *core_packages_version

  # Other dependencies
  "@chakra-ui/react": ^3.26.0
  "@chakra-ui/cli": ^3.26.0
  "@conterra/reactivity-core": ^0.7.0
  "@emotion/cache": ^11.14.0
  "@emotion/react": ^11.14.0
  "@emotion/styled": ^11.14.1
  "@formatjs/intl": ^3.1.6
  ol: ^10.6.1
  react-dom: *react_version
  react-icons: ^5.5.0
  react-use: ^17.6.0
  react: *react_version
  uuid: ^11.1.0

  # Devtools
  "@open-pioneer/build-package-cli": ^3.0.3
  "@open-pioneer/build-support": ^3.0.3
  "@open-pioneer/check-pnpm-duplicates": ^0.2.3
  "@open-pioneer/vite-plugin-pioneer": ^5.0.0
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.8.0
  "@testing-library/react": ^16.3.0
  "@testing-library/user-event": ^14.6.1
  "@types/js-yaml": ^4.0.9
  "@types/node": ^20.19.0
  "@types/react-dom": ^19.1.9
  "@types/react": ^19.1.12
  "@typescript-eslint/parser": ^8.43.0
  "@vitejs/plugin-react-swc": ^4.0.1
  eslint: ^9.35.0
  "@eslint/js": ^9.35.0
  "typescript-eslint": ^8.43.0
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-headers: ^1.3.3
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-unused-imports: ^4.2.0
  fast-glob: ^3.3.3
  handlebars: ^4.7.8
  happy-dom: ^18.0.1
  husky: ^9.1.7
  js-yaml: ^4.1.0
  jsdom: ^26.1.0
  lint-staged: ^16.1.6
  prettier: ^3.6.2
  rimraf: ^6.0.1
  sass: ^1.92.1
  tsx: ^4.20.5
  typedoc: ^0.28.12
  typescript: ^5.9.2
  vite: ^7.1.5
  vite-plugin-eslint: ^1.8.1
  vitest: ^3.2.4

overrides:
  # https://github.com/advisories/GHSA-v6h2-p8h4-qcjw
  "brace-expansion@>=1.0.0 <=1.1.11": "^1.1.12"
  "brace-expansion@>=2.0.0 <=2.0.1": "^2.0.2"

  # We don't actually use the babel plugin.
  # The babel runtime is also not used as a production dependency.
  # See e.g. https://github.com/emotion-js/emotion/issues/2371
  "@emotion/react>@emotion/babel-plugin": "-"
  "@emotion/styled>@emotion/babel-plugin": "-"
  "@emotion/react>@babel/runtime": "-"
  "@emotion/styled>@babel/runtime": "-"

  # Resolve duplicate packages
  "stylis@4.2.0": "^4.3.6"
  "source-map@0.5.6": "^0.6.1"

  # Ensure patched packages have the expected version (patch was tested with this version):
  "@ark-ui/react": "5.23.0"

auditConfig:
  ignoreCves:

allowUnusedPatches: true
ignorePatchFailures: false
patchedDependencies:
  # Ensure valids ids for aria-activedescendant and fix touch events in shadow DOM (see https://github.com/JedWatson/react-select/issues/5824)
  "react-select": "patches/react-select.patch"

  # - Ensure all portals are mounted under `.pioneer-root` div
  "@ark-ui/react@*": "patches/@ark-ui__react.patch"

peerDependencyRules:

# Only run build scripts for allowed packages.
dangerouslyAllowAllBuilds: false
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild

ignoredBuiltDependencies:
  # Seems to work fine without build script
  - core-js
  - unrs-resolver

# Don't automatically link to workspace packages (use e.g. "workspace:^" instead).
linkWorkspacePackages: false
autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: true

# Workaround for current problems regarding our vite plugin + vite's optimizeDeps feature
shamefullyHoist: true

# Cyclic dependencies are a code smell but should not trigger hard errors in pnpm.
ignoreWorkspaceCycles: true
