packages:
  - src/**
  - support/disabled-package
  - "!**/test-data/**"
  - "!**/dist/**"

# Shared version expressions (yaml anchors).
# This is a yaml feature and is not interpreted by pnpm directly.
__versions:
  - &react_version ^19.0.0
  - &core_packages_version ^3.0.0-dev.20250221111321
  - &ol_base_packages_version ^0.9.0-dev.20250224083536

# https://pnpm.io/catalogs
catalog:
  # Trails OpenLayers base packages
  # https://github.com/open-pioneer/trails-openlayers-base-packages
  "@open-pioneer/basemap-switcher": *ol_base_packages_version
  "@open-pioneer/coordinate-viewer": *ol_base_packages_version
  "@open-pioneer/geolocation": *ol_base_packages_version
  "@open-pioneer/map-navigation": *ol_base_packages_version
  "@open-pioneer/map-ui-components": *ol_base_packages_version
  "@open-pioneer/map": *ol_base_packages_version
  "@open-pioneer/measurement": *ol_base_packages_version
  "@open-pioneer/overview-map": *ol_base_packages_version
  "@open-pioneer/scale-bar": *ol_base_packages_version
  "@open-pioneer/scale-viewer": *ol_base_packages_version
  "@open-pioneer/theme": *ol_base_packages_version

  # Trails core packages
  # https://github.com/open-pioneer/trails-core-packages
  "@open-pioneer/base-theme": *core_packages_version
  "@open-pioneer/chakra-integration": *core_packages_version
  "@open-pioneer/core": *core_packages_version
  "@open-pioneer/http": *core_packages_version
  "@open-pioneer/integration": *core_packages_version
  "@open-pioneer/notifier": *core_packages_version
  "@open-pioneer/react-utils": *core_packages_version
  "@open-pioneer/runtime-react-support": *core_packages_version
  "@open-pioneer/runtime": *core_packages_version
  "@open-pioneer/test-utils": *core_packages_version

  # Other dependencies
  "@chakra-ui/icons": ^2.2.4
  "@chakra-ui/react": ^2.10.6
  "@emotion/cache": ^11.13.0
  "@emotion/react": ^11.13.0
  "@emotion/styled": ^11.13.0
  "@formatjs/intl": ^3.1.4
  framer-motion: ^12.4.7
  ol: ^10.4.0
  react-dom: *react_version
  react-icons: ^5.3.0
  react-use: ^17.5.1
  react: *react_version

  # Devtools
  "@open-pioneer/build-package-cli": ^3.0.0
  "@open-pioneer/build-support": ^3.0.0
  "@open-pioneer/vite-plugin-pioneer": ^4.0.0
  "@open-pioneer/check-pnpm-duplicates": "^0.2.0"
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.2
  "@testing-library/react": ^16.2.0
  "@testing-library/user-event": ^14.5.2
  "@types/js-yaml": ^4.0.9
  "@types/node": ^20.14.8
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  "@typescript-eslint/eslint-plugin": ^8.11.0
  "@typescript-eslint/parser": ^8.11.0
  "@vitejs/plugin-react-swc": ^3.7.1
  eslint-config-prettier: ^10.0.1
  eslint-import-resolver-typescript: ^3.6.3
  eslint-plugin-header: ^3.1.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.1
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react: ^7.37.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint: ^8.57.1
  fast-glob: ^3.3.3
  handlebars: ^4.7.8
  happy-dom: ^17.1.1
  husky: ^9.1.6
  js-yaml: ^4.1.0
  jsdom: ^26.0.0
  lint-staged: ^15.2.10
  prettier: ^3.3.3
  rimraf: ^6.0.1
  sass: ^1.85.0
  tsx: ^4.19.1
  typedoc: ^0.27.7
  typescript: ^5.7.3
  vite-plugin-eslint: ^1.8.1
  vite: ^6.1.1
  vitest: ^3.0.6
