packages:
  - src/**
  - support/disabled-package
  - "!**/test-data/**"
  - "!**/dist/**"

# Shared version expressions (yaml anchors).
# This is a yaml feature and is not interpreted by pnpm directly.
__versions:
  - &react_version ^18.3.1
  - &core_packages_version ^2.3.0
  - &ol_base_packages_version ^0.7.0

# https://pnpm.io/catalogs
catalog:
  # Trails OpenLayers base packages
  # https://github.com/open-pioneer/trails-openlayers-base-packages
  "@open-pioneer/basemap-switcher": *ol_base_packages_version
  "@open-pioneer/coordinate-viewer": *ol_base_packages_version
  "@open-pioneer/geolocation": *ol_base_packages_version
  "@open-pioneer/map-navigation": *ol_base_packages_version
  "@open-pioneer/map-ui-components": *ol_base_packages_version
  "@open-pioneer/map": *ol_base_packages_version
  "@open-pioneer/measurement": *ol_base_packages_version
  "@open-pioneer/overview-map": *ol_base_packages_version
  "@open-pioneer/scale-bar": *ol_base_packages_version
  "@open-pioneer/scale-viewer": *ol_base_packages_version
  "@open-pioneer/theme": *ol_base_packages_version

  # Trails core packages
  # https://github.com/open-pioneer/trails-core-packages
  "@open-pioneer/base-theme": *core_packages_version
  "@open-pioneer/chakra-integration": *core_packages_version
  "@open-pioneer/core": *core_packages_version
  "@open-pioneer/http": *core_packages_version
  "@open-pioneer/integration": *core_packages_version
  "@open-pioneer/notifier": *core_packages_version
  "@open-pioneer/react-utils": *core_packages_version
  "@open-pioneer/runtime-react-support": *core_packages_version
  "@open-pioneer/runtime": *core_packages_version
  "@open-pioneer/test-utils": *core_packages_version

  # Other dependencies
  "@chakra-ui/icons": ^2.2.4
  "@chakra-ui/react": ^2.8.2
  "@chakra-ui/system": ^2.6.2
  "@emotion/cache": ^11.13.0
  "@emotion/react": ^11.13.0
  "@emotion/styled": ^11.13.0
  "@formatjs/intl": ^2.10.4
  "@maplibre/maplibre-gl-style-spec": ^20.3.0
  framer-motion: ^11.3.11
  ol: ^9.2.4
  react-dom: *react_version
  react-icons: ^5.3.0
  react-use: ^17.5.1
  react: *react_version

  # Devtools
  "@open-pioneer/build-package-cli": ^2.1.1
  "@open-pioneer/build-support": ^2.0.2
  "@open-pioneer/vite-plugin-pioneer": ^3.0.5
  "@open-pioneer/check-pnpm-duplicates": "^0.1.0"
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.2
  "@testing-library/react": ^16.0.1
  "@testing-library/user-event": ^14.5.2
  "@types/js-yaml": ^4.0.9
  "@types/node": ^18.19.41
  "@types/react-dom": ^18.3.1
  "@types/react": ^18.3.11
  "@typescript-eslint/eslint-plugin": ^8.11.0
  "@typescript-eslint/parser": ^8.11.0
  "@vitejs/plugin-react-swc": ^3.7.1
  eslint-config-prettier: ^9.1.0
  eslint-import-resolver-typescript: ^3.6.3
  eslint-plugin-header: ^3.1.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.1
  eslint-plugin-react-hooks: ^4.6.2
  eslint-plugin-react: ^7.37.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint: ^8.57.0
  fast-glob: ^3.3.2
  handlebars: ^4.7.8
  happy-dom: ^15.7.4
  husky: ^9.1.6
  js-yaml: ^4.1.0
  jsdom: ^25.0.1
  lint-staged: ^15.2.10
  prettier: ^3.3.3
  rimraf: ^5.0.9
  sass: ^1.80.3
  tsx: ^4.19.1
  typedoc: ^0.26.10
  typescript: ~5.6.3
  vite-plugin-eslint: ^1.8.1
  vite: ^5.4.9
  vitest: ^2.1.3
