name: Audit dependencies (daily)

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  audit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          # Automatically uses version declared in package.json (`packageManager: pnpm@...`)
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Audit dependencies
        run: pnpm audit
